---
language: ruby
services:
  - docker
bundler_args: "--without system"
script: "bundle exec rspec --color --format documentation spec/unit"
notifications:
  email: false
sudo: false
jdk:
  - openjdk8
before_install: gem install bundler -v '< 2' --no-document
matrix:
  include:
    - stage: r10k tests
      rvm: 2.5.0
    - stage: r10k tests
      rvm: 2.4.0
    - stage: r10k tests
      rvm: 2.3.0
    - stage: r10k tests
      rvm: jruby
    - stage: r10k container tests
      language: generic
      script:
        - cd docker && make lint && make build && make test
