pool:
  # self-hosted agent on Windows 10 1709 environment
  # includes newer Docker engine with LCOW enabled, new build of LCOW image
  # includes Ruby 2.5, Go 1.10, Node.js 10.10, hadolint
  name: Default
# test double builds
variables:
  NAMESPACE: puppet

steps:
- checkout: self
  clean: true
- powershell: |
    $gemfile = Join-Path -Path (Get-Location) -ChildPath 'docker/Gemfile'
    $gempath = Join-Path -Path (Get-Location) -ChildPath 'docker/.bundle/gems'
    bundle config --local gemfile $gemfile
    bundle config --local path $gempath
    bundle install
  displayName: Fetch Dependencies
  name: fetch_deps
- powershell: |
    . "$(bundle show pupperware)/ci/build.ps1"
    Write-HostDiagnostics
  displayName: Diagnostic Host Information
  name: hostinfo
- powershell: |
    . "$(bundle show pupperware)/ci/build.ps1"
    Lint-Dockerfile -Name r10k -Ignore @('DL3028')
  displayName: Lint r10k Dockerfile
  name: lint_dockerfile
- powershell: |
    . "$(bundle show pupperware)/ci/build.ps1"
    Build-Container -Name r10k -Namespace $ENV:NAMESPACE
  displayName: Build r10k Container
  name: build_r10k_container
- powershell: |
    . "$(bundle show pupperware)/ci/build.ps1"
    Invoke-ContainerTest -Name r10k -Namespace $ENV:NAMESPACE
  displayName: Test r10k
  name: test_r10k
- task: PublishTestResults@2
  displayName: Publish r10k test results
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'docker/TEST-*.xml'
    testRunTitle: r10k Test Results
- powershell: |
    . "$(bundle show pupperware)/ci/build.ps1"
    Clear-ContainerBuilds -Name r10k -Namespace $ENV:NAMESPACE
  displayName: Container Cleanup
  condition: always()
